### ISSUE TITLE
Can you share source of find_object_2d?

### ISSUE THREAD

**Issue by yincanben** [introlab/find_object_2d-release#1]
I want to test find object project on our robot, but Google had closed the code service, Can you share source of find_object_2d  on github?

**Comment by matlabbe** [comment]
Yeah that was something I had to do, so I've made a branch called find_object_2d on the find_object project: https://github.com/introlab/find-object/tree/find_object_2d

Soon, all documentation of find_object would move in the github repository too.

cheers

**Comment by matlabbe** [comment]
Update: I've mostly moved all stuff to GitHub, the package is now directly on the master branch:  https://github.com/introlab/find-object/
